version: '3'
services:
  openvpn:
    container_name: openvpn
    build:
      context: .
      dockerfile: Dockerfile.arm32v7
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    ports:
      - "${BIND_OVPN_PORT}:1194/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    logging:
      #driver: "none"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    env_file:
      - .env


# vi: set et sts=2 si sw=2:
